#!/bin/bash

sudo -v # ask for password only at the beginning


#install homebrew
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"


#configure homebrew
brew update
brew upgrade
brew tap homebrew/versions
brew tap phinze/homebrew-cask


#install cli apps
brew install coreutils
brew install git
brew install vim
brew install mackup
brew install fish

#install gui apps (with cask)
brew cask install --appdir="/Applications" airfoil
brew cask install --appdir="/Applications" bartender
brew cask install --appdir="/Applications" calibre
#brew cask install --appdir="/Applications" cdock
brew cask install --appdir="/Applications" cord
brew cask install --appdir="/Applications" cyberduck
brew cask install --appdir="/Applications" disk-inventory-x
brew cask install --appdir="/Applications" dukto
brew cask install --appdir="/Applications" dropbox
brew cask install --appdir="/Applications" f-lux
brew cask install --appdir="/Applications" firefox
brew cask install --appdir="/Applications" flash
brew cask install --appdir="/Applications" gas-mask
brew cask install --appdir="/Applications" google-chrome
brew cask install --appdir="/Applications" google-drive
brew cask install --appdir="/Applications" hex-fiend
brew cask install --appdir="/Applications" hipchat
brew cask install --appdir="/Applications" istat-menus
brew cask install --appdir="/Applications" iterm2
brew cask install --appdir="/Applications" little-snitch
brew cask install --appdir="/Applications" multidoge
brew cask install --appdir="/Applications" mysql-workbench
brew cask install --appdir="/Applications" node
brew cask install --appdir="/Applications" sequel-pro
brew cask install --appdir="/Applications" silverlight
brew cask install --appdir="/Applications" skype
brew cask install --appdir="/Applications" spotifree
brew cask install --appdir="/Applications" spotify
brew cask install --appdir="/Applications" sqlitebrowser
brew cask install --appdir="/Applications" sublime-text3
brew cask install --appdir="/Applications" testflight
brew cask install --appdir="/Applications" the-unarchiver
brew cask install --appdir="/Applications" utorrent
brew cask install --appdir="/Applications" vagrant
brew cask install --appdir="/Applications" virtualbox
brew cask install --appdir="/Applications" vlc
brew cask install --appdir="/Applications" wireshark
brew cask install --appdir="/Applications" witch
brew cask install --appdir="/Applications" xquartz
brew cask install --appdir="/Applications" ynab


#custom quicklooks
brew cask install --appdir="/Applications" betterzipql
brew cask install --appdir="/Applications" ipaql
brew cask install --appdir="/Applications" qlcolorcode
brew cask install --appdir="/Applications" qlstephen
brew cask install --appdir="/Applications" qlmarkdown
brew cask install --appdir="/Applications" quicklook-json
brew cask install --appdir="/Applications" qlprettypatch
brew cask install --appdir="/Applications" quicklook-csv
brew cask install --appdir="/Applications" webp-quicklook
brew cask install --appdir="/Applications" suspicious-package


#link sublime for global 'sublime' command
ln -s /opt/homebrew-cask/Caskroom/sublime-text3/Build 3059/Sublime Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl

#install capistrano
gem sources -a http://gems.github.com/

#note - sticking to capistrano v2 for now...
sudo gem install capistrano -v "=2.15.5"

#install vagrant-cachier (to speed up provisioning)
vagrant plugin install vagrant-cachier