#!/bin/bash

sudo -v # ask for password only at the beginning


# install brew
echo "installing homebrew..."
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# configure homebrew
brew update
brew upgrade
brew tap caskroom/versions
brew tap phinze/homebrew-cask
brew tap mas-cli/tap
brew tap-pin mas-cli/tap
brew tap caskroom/fonts


# install brew cli apps
echo "installing cli apps..."
binaries=(
  android-sdk
  ant
  coreutils
  curl
  fish
  git
  java
  mackup
  mas
  nvm
  openssl
  vagrant
  vim
  wget
  yarn
)

brew install ${binaries[@]}


# install gui apps (with cask)
echo "installing gui apps..."
apps=(
  calibre
  colorpicker
  cyberduck
  datagrip
  disk-inventory-x
  diffmerge
  divvy
  docker
  docker-machine
  dropbox
  dukto
  firefox
  gimp
  google-chrome
  google-drive-file-stream
  harvest
  hex-fiend
  istat-menus
  iterm2
  postman
  sequel-pro
  shimo
  skype
  spotify
  slack
  sqlitebrowser
  sublime-text3
  the-unarchiver
  utorrent
  vagrant
  virtualbox
  visual-studio-code
  vlc
  wireshark
  witch
  xquartz
  ynab
)

brew cask install --appdir="/Applications" ${apps[@]}


# install mas (mac appstore) apps
echo "installing mac appstore apps..."
masapps=(
  1295203466 #Microsoft Remote Desktop 10 (10.2.3)
  497799835 #XCode
)
mas install ${masapps[@]}

# install custom quicklooks
echo "installing custom quicklooks..."
quicklooks=(
  betterzipql
  ipaql
  qlcolorcode
  qlmarkdown
  qlprettypatch
  qlstephen
  quicklook-csv
  quicklook-json
  suspicious-package
  webp-quicklook
)

mas install ${quicklooks[@]}


# install fonts
echo "installing fonts..."
fonts=(
  font-geo-sans-light
  font-source-code-pro
  font-roboto
  brew cask install font-fira-code
)

brew cask install ${fonts[@]}


# cleanup
brew cleanup

# install the latest LTS of node
nvm install --lts
nvm use node

# allow NVM in every shell session
export NVM_DIR="$HOME/.nvm"
. "$(brew --prefix nvm)/nvm.sh"


# install capistrano 2.15.5 for legacy deployments
gem sources -a http://gems.github.com/
sudo gem install capistrano -v "=2.15.5"

# install cocoapods
sudo gem install cocoapods

# install vagrant plugins
vagrant plugin install vagrant-bindfs
vagrant plugin install vagrant-cachier
vagrant plugin install vagrant-gatling-rsync
vagrant plugin install vagrant-hostsupdater
