#!/bin/bash

sudo -v # ask for password only at the beginning


#install
echo "installing homebrew..."
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"


#configure homebrew
brew update
brew upgrade
#brew tap homebrew/versions
brew tap caskroom/versions
brew tap phinze/homebrew-cask


#install cli apps
binaries=(
  android-sdk
  ant
  coreutils
  fish
  git
  mackup
  openssl
  vim
  wget
)

echo "installing binaries..."
brew install ${binaries[@]}



#install gui apps (with cask)
apps=(
  atom
  bartender
  calibre
  caffeine
  cord
  colorpicker 
  cyberduck
  disk-inventory-x
  diffmerge
  divvy
  dropbox
  dukto
  flux
  firefox
  flash
  google-chrome
  google-drive
  gimp
  hex-fiend
  istat-menus
  iterm2
  java7
  node
  sequel-pro
  silverlight
  skype
  spotifree
  spotify
  slack
  sqlitebrowser
  sublime-text
  the-unarchiver
  utorrent
  vagrant
  virtualbox
  vlc
  wireshark
  witch
  xquartz
  ynab
)

echo "installing gui apps..."
brew cask install --appdir="/Applications" ${apps[@]}


#custom quicklooks
quicklooks=(
  betterzipql
  ipaql
  qlcolorcode
  qlmarkdown
  qlprettypatch
  qlstephen
  quicklook-csv
  quicklook-json
  suspicious-package
  webp-quicklook
)

echo "installing custom quicklooks..."
brew cask install --appdir="/Applications" ${quicklooks[@]}


#fonts
#The font recipes are prefixed by font-*, so if you want to download Roboto, try searching for font-roboto:

brew tap caskroom/fonts

fonts=(
  font-geo-sans-light
  font-source-code-pro
  font-roboto
)

# install fonts
echo "installing fonts..."
brew cask install ${fonts[@]}





#cleanup
brew cleanup


#link sublime for global 'sublime' command
ln -s /opt/homebrew-cask/Caskroom/sublime-text3/Build 3059/Sublime Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl

#install capistrano
gem sources -a http://gems.github.com/

#note - sticking to capistrano v2 for now...
sudo gem install capistrano -v "=2.15.5"

#install cocoapods
sudo gem install cocoapods

#install vagrant-cachier (to speed up provisioning)
vagrant plugin install vagrant-cachier
